//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_quality_assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassCriterion
    {
        public int Id { get; set; }
        public int CriterionId { get; set; }
        public int ClassId { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual Class Class { get; set; }
    }
}
