//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program_quality_assessment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Metrics> MetricsSet { get; set; }
        public virtual DbSet<Factor> FactorSet { get; set; }
        public virtual DbSet<Criterion> CriterionSet { get; set; }
        public virtual DbSet<Element> ElementSet { get; set; }
        public virtual DbSet<Phase> PhaseSet { get; set; }
        public virtual DbSet<Class> ClassSet { get; set; }
        public virtual DbSet<ClassCriterion> ClassCriterionSet { get; set; }
        public virtual DbSet<PhaseMetrics> PhaseMetricsSet { get; set; }
    }
}
